name: Test 1 - Normal Flow (Known CSPM URL)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  aqua-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Aqua scanner - Normal Flow
        uses: docker://aquasec/aqua-scanner:dev
        with:
          args: trivy fs --scanners vuln,secret .
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          AQUA_URL: https://api.dev.supply-chain.cloud.aquasec.com
          CSPM_URL: https://stage.api.cloudsploit.com
          TRIVY_RUN_AS_PLUGIN: aqua
